name: FRC Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: FRC Build
      uses: markebert/FRC-actions@v2.1
      with:
        build_mode: 'build'